"""
AgriEdge — ESP32 Node Simulator

Replaces physical ESP32 sensor and camera nodes for the hackathon demo.
Generates plausible sensor readings and posts leaf images to the backend
ingest endpoints via HTTP POST.

This simulator sends the EXACT SAME message schema that our real ESP32
firmware will send. Swapping in real hardware means changing zero lines
of backend code — only this script gets replaced by physical nodes.

HTTP POST is used instead of MQTT for simplicity. Swapping to a real
MQTT broker (Mosquitto) is a drop-in replacement: the backend would
subscribe to `agriedge/sensors/#` and `agriedge/images/#` topics instead
of exposing HTTP ingest routes. The message payloads remain identical.

Usage:
    python simulator/run_simulator.py
    python simulator/run_simulator.py --interval 5 --image-interval 20
"""

import os
import sys
import time
import json
import random
import base64
import argparse
import requests

# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------
SEED = 42
random.seed(SEED)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BACKEND_URL = "http://localhost:8000"
SENSOR_ENDPOINT = f"{BACKEND_URL}/ingest/sensor"
IMAGE_ENDPOINT = f"{BACKEND_URL}/ingest/image"

# Field zones — 5 sensor nodes + 5 camera nodes
SENSOR_NODES = ["node-01", "node-02", "node-03", "node-04"]
CAMERA_NODES = ["cam-01", "cam-02", "cam-03", "cam-04"]

# Path to mock leaf images generated by ml_training/generate_mock_dataset.py
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..")
LEAF_IMAGE_DIR = os.path.join(PROJECT_ROOT, "ml_training", "data", "leaf_images")


# ---------------------------------------------------------------------------
# Random-walk state for each sensor node
# ---------------------------------------------------------------------------
class NodeState:
    """Maintains realistic random-walk state for a single sensor node."""

    def __init__(self, node_id: str):
        self.node_id = node_id

        # Initial values — slightly randomised per node
        self.soil_moisture = 0.4 + random.uniform(-0.1, 0.1)
        self.n = random.randint(10, 20)
        self.p = random.randint(5, 15)
        self.k = random.randint(15, 25)
        self.gas_voc = 100 + random.uniform(-30, 30)
        self.temp_c = 28 + random.uniform(-3, 3)

    def step(self):
        """Advance one time step with random-walk variation."""
        # Soil moisture: walk +/- 0.02, clamp [0.1, 0.9]
        self.soil_moisture += random.uniform(-0.02, 0.02)
        self.soil_moisture = max(0.1, min(0.9, self.soil_moisture))

        # NPK: walk +/- 1-2, clamp [5, 50]
        self.n = max(5, min(50, self.n + random.randint(-2, 2)))
        self.p = max(5, min(50, self.p + random.randint(-1, 1)))
        self.k = max(5, min(50, self.k + random.randint(-2, 2)))

        # Gas VOC: walk +/- 5, clamp [50, 300]
        # 15% chance of severe anomalous spike to 600-800 to ensure fusion engine alerts fire
        if random.random() < 0.15:
            self.gas_voc = random.uniform(600, 800)
        else:
            self.gas_voc += random.uniform(-5, 5)
            self.gas_voc = max(50, min(300, self.gas_voc))

        # Temperature: walk +/- 0.5, clamp [20, 45]
        self.temp_c += random.uniform(-0.5, 0.5)
        self.temp_c = max(20, min(45, self.temp_c))

    def to_payload(self) -> dict:
        """Generate payload matching the real ESP32 sensor schema."""
        return {
            "node_id": self.node_id,
            "ts": int(time.time()),
            "soil_moisture": round(self.soil_moisture, 3),
            "npk": {
                "n": self.n,
                "p": self.p,
                "k": self.k,
            },
            "gas_voc": round(self.gas_voc, 1),
            "temp_c": round(self.temp_c, 1),
        }


# ---------------------------------------------------------------------------
# Image helpers
# ---------------------------------------------------------------------------
def _get_random_image_b64() -> str | None:
    """Pick a random leaf image from the mock dataset and return as base64."""
    try:
        # Collect all images
        images = []
        for category in ["healthy", "diseased"]:
            cat_dir = os.path.join(LEAF_IMAGE_DIR, category)
            if os.path.isdir(cat_dir):
                for fname in os.listdir(cat_dir):
                    if fname.endswith(".png"):
                        images.append(os.path.join(cat_dir, fname))

        if not images:
            print("[sim] WARNING: No leaf images found. Run generate_mock_dataset.py first.")
            return None

        chosen = random.choice(images)
        with open(chosen, "rb") as f:
            return base64.b64encode(f.read()).decode("ascii")
    except Exception as exc:
        print(f"[sim] Image load error: {exc}")
        return None


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
def run_simulator(sensor_interval: int = 10, image_interval: int = 45):
    """
    Run the simulator loop.

    Args:
        sensor_interval: seconds between sensor payload batches
        image_interval: approximate seconds between image submissions
    """
    print("=" * 60)
    print("AgriEdge -- ESP32 Node Simulator")
    print("=" * 60)
    print(f"  Backend:          {BACKEND_URL}")
    print(f"  Sensor nodes:     {', '.join(SENSOR_NODES)}")
    print(f"  Camera nodes:     {', '.join(CAMERA_NODES)}")
    print(f"  Sensor interval:  {sensor_interval}s")
    print(f"  Image interval:   ~{image_interval}s")
    print(f"  Leaf image dir:   {LEAF_IMAGE_DIR}")
    print("=" * 60)
    print()

    # Verify backend is reachable
    try:
        r = requests.get(f"{BACKEND_URL}/", timeout=5)
        if r.status_code == 200:
            print("[sim] Backend is reachable. Starting simulation...")
        else:
            print(f"[sim] WARNING: Backend returned status {r.status_code}")
    except requests.exceptions.ConnectionError:
        print(f"[sim] ERROR: Cannot reach backend at {BACKEND_URL}")
        print("      Start the backend first: uvicorn backend.api.main:app --port 8000")
        sys.exit(1)

    # Initialise node states
    nodes = {nid: NodeState(nid) for nid in SENSOR_NODES}
    tick = 0
    last_image_time = 0

    print()
    try:
        while True:
            tick += 1
            now = time.time()

            # --- Send sensor payloads for all nodes ---
            print(f"--- Tick {tick} ({time.strftime('%H:%M:%S')}) ---")
            for nid, state in nodes.items():
                state.step()
                payload = state.to_payload()

                try:
                    r = requests.post(
                        SENSOR_ENDPOINT,
                        json=payload,
                        timeout=5,
                    )
                    status_str = "OK" if r.status_code == 200 else f"ERR:{r.status_code}"
                    voc_marker = " *** VOC SPIKE ***" if payload["gas_voc"] > 350 else ""
                    print(
                        f"  [sensor] {nid}  "
                        f"sm={payload['soil_moisture']:.2f}  "
                        f"temp={payload['temp_c']:.1f}C  "
                        f"voc={payload['gas_voc']:.0f}  "
                        f"npk=({payload['npk']['n']},{payload['npk']['p']},{payload['npk']['k']})  "
                        f"[{status_str}]{voc_marker}"
                    )
                except requests.exceptions.RequestException as exc:
                    print(f"  [sensor] {nid} SEND FAILED: {exc}")

            # --- Send image payload periodically ---
            if now - last_image_time >= image_interval:
                cam_node = random.choice(CAMERA_NODES)
                image_b64 = _get_random_image_b64()

                if image_b64:
                    image_payload = {
                        "node_id": cam_node,
                        "ts": int(now),
                        "image_b64": image_b64,
                        "trigger": "scheduled",
                    }

                    try:
                        r = requests.post(
                            IMAGE_ENDPOINT,
                            json=image_payload,
                            timeout=15,
                        )
                        if r.status_code == 200:
                            result = r.json()
                            fusion = result.get("fusion", {})
                            alert = result.get("alert")
                            alert_str = f"ALERT {alert['alert_id']} ({alert['type']})" if alert else "no alert"
                            print(
                                f"  [image]  {cam_node}  "
                                f"score={fusion.get('score', '?')}  "
                                f"tier={fusion.get('tier', '?')}  "
                                f"{alert_str}"
                            )
                        else:
                            print(f"  [image]  {cam_node} ERR:{r.status_code} {r.text[:100]}")
                    except requests.exceptions.RequestException as exc:
                        print(f"  [image]  {cam_node} SEND FAILED: {exc}")

                last_image_time = now

            print()
            time.sleep(sensor_interval)

    except KeyboardInterrupt:
        print("\n[sim] Simulator stopped by user.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="AgriEdge ESP32 Node Simulator")
    parser.add_argument("--interval", type=int, default=10,
                        help="Seconds between sensor batches (default: 10)")
    parser.add_argument("--image-interval", type=int, default=45,
                        help="Approx seconds between image submissions (default: 45)")
    args = parser.parse_args()
    run_simulator(sensor_interval=args.interval, image_interval=args.image_interval)


if __name__ == "__main__":
    main()
