"""
AgriEdge — Model Training Script

Trains two scikit-learn classifiers on the mock dataset generated by
generate_mock_dataset.py:

1. Disease classifier (RandomForestClassifier)
   - Features: 24-bin RGB color histogram + 3 GLCM texture stats = 27 features
   - Labels: healthy (0) / diseased (1)
   - Output: backend/models/disease_clf.pkl

2. Gas-anomaly classifier (RandomForestClassifier)
   - Features: VOC, temp_c, humidity
   - Labels: healthy (0) / anomalous (1)
   - Output: backend/models/gas_clf.pkl

NOTE: These models are trained on procedurally generated mock data.
The production version trains on PlantVillage + real field images and
actual sensor logs from deployed ESP32 nodes.

All random generation is seeded for reproducibility.
"""

import os
import sys
import pickle
import warnings

import numpy as np
import pandas as pd
from PIL import Image

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Suppress non-critical warnings for clean demo output
warnings.filterwarnings("ignore", category=UserWarning)

# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
LEAF_DIR = os.path.join(DATA_DIR, "leaf_images")
GAS_CSV = os.path.join(DATA_DIR, "gas_data.csv")

PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..")
MODELS_DIR = os.path.join(PROJECT_ROOT, "backend", "models")


# =====================  FEATURE EXTRACTION  ================================

def extract_leaf_features(image_path: str) -> np.ndarray:
    """
    Extract a 27-dimensional feature vector from a leaf image:
      - RGB color histogram (8 bins per channel = 24 features)
      - GLCM texture statistics (contrast, homogeneity, energy = 3 features)
    """
    try:
        img = Image.open(image_path).convert("RGB").resize((64, 64))
        arr = np.array(img)

        # --- Color histogram (8 bins × 3 channels = 24 features) ---
        hist_features = []
        for ch in range(3):
            hist, _ = np.histogram(arr[:, :, ch], bins=8, range=(0, 256))
            hist = hist.astype(float) / hist.sum()  # normalize
            hist_features.extend(hist)

        # --- GLCM texture stats (3 features) ---
        # Using scikit-image greycomatrix / greycoprops
        try:
            from skimage.feature import graycomatrix, graycoprops
        except ImportError:
            # Older scikit-image versions
            from skimage.feature import greycomatrix as graycomatrix
            from skimage.feature import greycoprops as graycoprops

        gray = np.mean(arr, axis=2).astype(np.uint8)
        glcm = graycomatrix(gray, distances=[1], angles=[0],
                            levels=256, symmetric=True, normed=True)
        contrast = graycoprops(glcm, "contrast")[0, 0]
        homogeneity = graycoprops(glcm, "homogeneity")[0, 0]
        energy = graycoprops(glcm, "energy")[0, 0]

        texture_features = [contrast, homogeneity, energy]

        return np.array(hist_features + texture_features, dtype=np.float64)

    except Exception as exc:
        print(f"  [warn] Feature extraction failed for {image_path}: {exc}")
        return np.zeros(27, dtype=np.float64)


# =====================  DISEASE CLASSIFIER  ================================

def train_disease_model():
    """Train the leaf disease classifier and save as .pkl."""
    print("\n--- Disease Classifier ---")

    healthy_dir = os.path.join(LEAF_DIR, "healthy")
    diseased_dir = os.path.join(LEAF_DIR, "diseased")

    if not os.path.isdir(healthy_dir) or not os.path.isdir(diseased_dir):
        print("[error] Leaf image directories not found.")
        print("        Run  python ml_training/generate_mock_dataset.py  first.")
        sys.exit(1)

    X, y = [], []

    # Healthy images -> label 0
    healthy_files = sorted([f for f in os.listdir(healthy_dir) if f.endswith(".png")])
    print(f"  Loading {len(healthy_files)} healthy images...")
    for fname in healthy_files:
        feats = extract_leaf_features(os.path.join(healthy_dir, fname))
        X.append(feats)
        y.append(0)

    # Diseased images -> label 1
    diseased_files = sorted([f for f in os.listdir(diseased_dir) if f.endswith(".png")])
    print(f"  Loading {len(diseased_files)} diseased images...")
    for fname in diseased_files:
        feats = extract_leaf_features(os.path.join(diseased_dir, fname))
        X.append(feats)
        y.append(1)

    X = np.array(X)
    y = np.array(y)

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=SEED, stratify=y
    )

    clf = RandomForestClassifier(n_estimators=100, random_state=SEED)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"  Accuracy: {acc:.2%}")
    print(classification_report(y_test, y_pred,
                                target_names=["healthy", "diseased"],
                                zero_division=0))

    # Save model
    os.makedirs(MODELS_DIR, exist_ok=True)
    model_path = os.path.join(MODELS_DIR, "disease_clf.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(clf, f)
    print(f"  Saved -> {os.path.abspath(model_path)}")
    return acc


# =====================  GAS CLASSIFIER  ====================================

def train_gas_model():
    """Train the gas-anomaly classifier and save as .pkl."""
    print("\n--- Gas-Anomaly Classifier ---")

    if not os.path.isfile(GAS_CSV):
        print("[error] Gas data CSV not found.")
        print("        Run  python ml_training/generate_mock_dataset.py  first.")
        sys.exit(1)

    df = pd.read_csv(GAS_CSV)
    print(f"  Loaded {len(df)} samples")

    X = df[["voc", "temp_c", "humidity"]].values
    y = df["label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=SEED, stratify=y
    )

    clf = RandomForestClassifier(n_estimators=100, random_state=SEED)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"  Accuracy: {acc:.2%}")
    print(classification_report(y_test, y_pred,
                                target_names=["healthy", "anomalous"],
                                zero_division=0))

    model_path = os.path.join(MODELS_DIR, "gas_clf.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(clf, f)
    print(f"  Saved -> {os.path.abspath(model_path)}")
    return acc


# =====================  MAIN  ==============================================

def main():
    print("=" * 60)
    print("AgriEdge — Model Training")
    print("=" * 60)

    try:
        disease_acc = train_disease_model()
        gas_acc = train_gas_model()

        print()
        print("=" * 60)
        print(f"  Disease classifier accuracy:  {disease_acc:.2%}")
        print(f"  Gas classifier accuracy:      {gas_acc:.2%}")
        print("=" * 60)
        print("[train] OK: All models trained and saved successfully.")
    except Exception as exc:
        print(f"\n[train] FAIL: ERROR: {exc}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
